export type PlanCode = "basic" | "pro" | "studio";
export type PlanRow = { label: string; value: string };
export type Plan = { code: PlanCode; name: string; priceLabel: string; monthlyPrice: string; pitch: string; featured: boolean; rows: PlanRow[] };

export const trialDays = 3;

export const trialLimits = {
  keyword_expand: 5,
  annotation_explorer: 2,
  top_pins: 1,
  account_explorer: 2,
  board_explorer: 2,
  research_project: 1,
  rank_tracker: 2,
  search_tracker: 2,
  max_pins_per_search: 100,
  stored_projects: 3,
  tracker_history_days: 3,
} as const;

export const plans: Plan[] = [
  {
    code: "basic", name: "Basic", monthlyPrice: "10", priceLabel: "$10",
    pitch: "A complete research toolkit for individual creators and beginners.", featured: false,
    rows: [
      { label: "Keyword Explorer", value: "20/day" },
      { label: "Ideas searches", value: "5/day" },
      { label: "Top Pins credits", value: "3/day" },
      { label: "Pin statistics", value: "Included" },
      { label: "Account Explorer", value: "5/day" },
      { label: "Board Explorer", value: "5/day" },
      { label: "Project collections", value: "2/day" },
      { label: "Manual rank checks", value: "5/day" },
      { label: "Manual search checks", value: "5/day" },
      { label: "Idea measurements", value: "Included" },
      { label: "Project image analysis", value: "Included" },
      { label: "Maximum pins/search", value: "100" },
      { label: "Stored projects", value: "10" },
      { label: "Tracker history", value: "30 days" },
      { label: "Saved lists", value: "25" },
      { label: "Saved items", value: "2,500" },
      { label: "Automatic tracker checks", value: "Daily" },
      { label: "Exports & cached results", value: "Unlimited" },
    ],
  },
  {
    code: "pro", name: "Pro", monthlyPrice: "25", priceLabel: "$25",
    pitch: "3× Basic’s daily research and storage capacity for serious creators and marketers.", featured: true,
    rows: [
      { label: "Keyword Explorer", value: "60/day" },
      { label: "Ideas searches", value: "15/day" },
      { label: "Top Pins credits", value: "9/day" },
      { label: "Pin statistics", value: "Included" },
      { label: "Account Explorer", value: "15/day" },
      { label: "Board Explorer", value: "15/day" },
      { label: "Project collections", value: "6/day" },
      { label: "Manual rank checks", value: "15/day" },
      { label: "Manual search checks", value: "15/day" },
      { label: "Idea measurements", value: "Included" },
      { label: "Project image analysis", value: "Included" },
      { label: "Maximum pins/search", value: "300" },
      { label: "Stored projects", value: "30" },
      { label: "Tracker history", value: "90 days" },
      { label: "Saved lists", value: "75" },
      { label: "Saved items", value: "7,500" },
      { label: "Automatic tracker checks", value: "Daily" },
      { label: "Exports & cached results", value: "Unlimited" },
    ],
  },
  {
    code: "studio", name: "Studio", monthlyPrice: "80", priceLabel: "$80",
    pitch: "10× Basic’s daily research and storage capacity for agencies and high-volume work.", featured: false,
    rows: [
      { label: "Keyword Explorer", value: "200/day" },
      { label: "Ideas searches", value: "50/day" },
      { label: "Top Pins credits", value: "30/day" },
      { label: "Pin statistics", value: "Included" },
      { label: "Account Explorer", value: "50/day" },
      { label: "Board Explorer", value: "50/day" },
      { label: "Project collections", value: "20/day" },
      { label: "Manual rank checks", value: "50/day" },
      { label: "Manual search checks", value: "50/day" },
      { label: "Idea measurements", value: "Included" },
      { label: "Project image analysis", value: "Included" },
      { label: "Maximum pins/search", value: "500" },
      { label: "Stored projects", value: "100" },
      { label: "Tracker history", value: "365 days" },
      { label: "Saved lists", value: "250" },
      { label: "Saved items", value: "25,000" },
      { label: "Automatic tracker checks", value: "Daily" },
      { label: "Exports & cached results", value: "Unlimited" },
    ],
  },
];
